apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: imager-client
  name: imager-client
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: imager-client
  template:
    metadata:
      labels:
        app: imager-client
    spec:
      containers:
      - name: imager-client
        image: imager-client:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 60