apiVersion: v1
kind: Service
metadata:
  name: imager-server
  labels:
    app: imager-server
spec:
  type: NodePort
  selector:
    app: imager-server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imager-database
  labels:
    app: imager-database
spec:
  clusterIP: None
  selector:
    app: imager-database